### ISSUE TITLE
Failed in setup

### ISSUE THREAD

**Issue by yangmin27** [mamunm/BayesianFramework#2]
hello, when I do python3 setup.py install -- command, it failed by this error:

error: Could not find suitable distribution for Requirement.parse('sklearn>=0.20.1')
but actually I already installed sklearn

**Comment by mamunm** [comment]
Hi, most likely it's because of the python version. Either you can downgrade python or use an environment. Please see this answer for further details: https://stackoverflow.com/questions/59938365/python-setup-py-could-not-find-suitable-distribution-for-requirement-parseten
